/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.salesdb.models.query.*;

@Service
public class SalesdbQueryExecutorServiceImpl implements SalesdbQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SalesdbQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("salesdbWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Page<TotalLeadsResponse> executeTotalLeads(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("totalLeads", params, TotalLeadsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Downloadable exportTotalLeads(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("totalLeads", params, exportType, TotalLeadsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Page<SalesByRepsResponse> executeSalesByReps(Integer channel, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("channel", channel);

        return queryExecutor.executeNamedQuery("salesByReps", params, SalesByRepsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Downloadable exportSalesByReps(ExportType exportType, Integer channel, Pageable pageable) {
        Map params = new HashMap(1);

        params.put("channel", channel);

        return queryExecutor.exportNamedQueryData("salesByReps", params, exportType, SalesByRepsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Page<TopTrendingProductsResponse> executeTopTrendingProducts(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("topTrendingProducts", params, TopTrendingProductsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Downloadable exportTopTrendingProducts(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("topTrendingProducts", params, exportType, TopTrendingProductsResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Page<TotalSalesAndRevenueResponse> executeTotalSalesAndRevenue(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("totalSalesAndRevenue", params, TotalSalesAndRevenueResponse.class, pageable);
    }

    @Transactional(readOnly = true, value = "salesdbTransactionManager")
    @Override
    public Downloadable exportTotalSalesAndRevenue(ExportType exportType, Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.exportNamedQueryData("totalSalesAndRevenue", params, exportType, TotalSalesAndRevenueResponse.class, pageable);
    }

}


