/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/

package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.salesdb.models.query.*;

public interface SalesdbQueryExecutorService {

    Page<TotalLeadsResponse> executeTotalLeads(Pageable pageable);

    Downloadable exportTotalLeads(ExportType exportType, Pageable pageable);

    Page<SalesByRepsResponse> executeSalesByReps(Integer channel, Pageable pageable);

    Downloadable exportSalesByReps(ExportType exportType, Integer channel, Pageable pageable);

    Page<TopTrendingProductsResponse> executeTopTrendingProducts(Pageable pageable);

    Downloadable exportTopTrendingProducts(ExportType exportType, Pageable pageable);

    Page<TotalSalesAndRevenueResponse> executeTotalSalesAndRevenue(Pageable pageable);

    Downloadable exportTotalSalesAndRevenue(ExportType exportType, Pageable pageable);

}


